Worksheet Generator Feature PR
marvelai-org/marvel-ai-backend pull request #102
Opened 2024-09-04 03:41 UTC by vash02

2024-09-04 04:40 UTC, hash2004 requested changes
Please add description to your PR as well.  You can use this [pull request as inspiration](https://github.com/radicalxdev/marvel-ai-backend/pull/101).

2024-09-04 04:40 UTC, hash2004 commented on app/utils/auth.py
> +  print("api key",api_key)
Do not print the environment variables anywhere. It is unsafe and is not good practice.

2024-09-04 04:40 UTC, hash2004 commented on app/utils/auth.py
> +  print("env type",os.environ['ENV_TYPE'])
Using print statements to display environment variables, such as `print("env type", os.environ['ENV_TYPE'])`, is not considered a best practice. Printing sensitive information like environment types can lead to security risks and clutter the output with unnecessary details. Instead, consider using proper logging frameworks or avoid printing such values unless absolutely necessary.

2024-11-17 15:20 UTC, AaronSosaRamos requested changes
Please, solve the given comments

2024-11-17 15:20 UTC, AaronSosaRamos commented on app/features/worksheet_generator/README.md
> +## Example Usage
Good README.md. You can try adding the request and response interfaces for enabling a better understanding of what the dev team can expect to interact with during the requests to the AI endpoint.

2024-11-17 15:20 UTC, AaronSosaRamos commented on app/features/worksheet_generator/core.py
> +def executor(files: list[ToolFile], topic: str, level: str, hint: str, hint_num: int, num_questions: int, verbose=True):
You can use a Pydantic schema for decoupling the args.

2024-11-17 15:20 UTC, AaronSosaRamos commented on app/features/worksheet_generator/core.py
> +        pipeline = RAGpipeline(verbose=verbose)
Chage the name of this class as it does not support a complete understanding of what it does for the Worksheet Generator.

2024-11-17 15:20 UTC, AaronSosaRamos commented on app/features/worksheet_generator/core.py
> +        output = WorksheetBuilder(db, topic, level, hint, "quiz").create_questions(num_questions)
You can instantiate your WorksheetBuilder class first instead for reusing the same variable and improve the readability.

2024-11-17 15:20 UTC, AaronSosaRamos commented on app/features/worksheet_generator/prompt/worksheet-generator-worksheet-prompt.txt
What's the difference between this file and the other `worksheet-generator-quiz-prompt.txt`? If they are different, please make sure to use different names for better readability.

2024-11-17 15:20 UTC, AaronSosaRamos commented on app/features/worksheet_generator/thebook.pdf
Why is this file required?

2024-11-17 15:20 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +            "model": VertexAI(model="gemini-1.0-pro"),
VertexAI is not used anymore in the main project.

2024-11-17 15:20 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +    def __init__(self, db, topic, level=None, hint=None, q_type=""):
You can create a Pydantic schema for decoupling the args.

2024-11-17 15:20 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +        runner = RunnableParallel({"context": retriever, "topic":RunnablePassthrough(), "hint": RunnablePassthrough(),
Good parallelization of the AI pipeline.

2024-11-17 15:20 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +    def validate_response(self, response: dict) -> bool:
This is not required as the JSONOutputParser supports this.

2024-11-17 15:20 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +    def validate_worksheet_response(self, response: dict) -> bool:
This is not required as the JSONOutputParser supports this.

2024-11-17 15:20 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +    def is_valid_dict_values(self, json_dict):
This is not required as the JSONOutputParser supports this.

2024-11-17 15:20 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +    def format_choices(self, choices: Dict[str, str]) -> List[Dict[str, str]]:
This is not required as the JSONOutputParser supports this.

2024-11-17 15:20 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +        while len(generated_questions) < num_questions and attempts < max_attempts:
Ensure that this while loop is not costful for optimal results.

2024-11-17 15:20 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +    def validate_qtype_response(self, hint: str, answer) -> bool:
This is not required as the JSONOutputParser supports this.

2024-11-17 15:20 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +    def is_response_relevant(self, response: dict) -> bool:
This proposal is interesting but costful in terms of production resources. Indeed, Google actually provides metrics to accomplish this semantic search process with their embeddings.

2024-11-17 15:20 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +        while len(generated_questions) < hint_num and attempts < max_attempts:
Ensure that this while loop is not costful in terms of token generation.

2024-11-17 15:20 UTC, AaronSosaRamos commented on app/utils/auth.py
> +  if api_key is None:
Please, remove this as it is affecting the auth. of the AI endpoint.

2024-12-18 20:53 UTC, closed without merging

2024-12-18 20:53 UTC, AaronSosaRamos commented
Closed due inactivity