Unit tests for tools.py
marvelai-org/marvel-ai-backend pull request #70
Opened 2024-07-09 23:00 UTC by ayushrawat6367

Updated tests for Ragpipeline and Quizbuilder classes.

2024-08-27 18:40 UTC, hash2004 requested changes

2024-08-27 18:40 UTC, hash2004 commented on Dockerfile
> +ENV PROJECT_ID="heroic-climber-423918-r1"
Hard coding ENV variables is not best practice.

2024-08-27 18:40 UTC, hash2004 commented on app/api/router.py
> +        print("Before finalize_inputs")
Use logger for these types of print statements.

2024-08-27 18:40 UTC, hash2004 commented on app/api/tests/test_tools.py
> +    # os.environ['PROJECT_ID'] = "kai-ai-f63c8"
Remove comments like these

2024-08-27 18:40 UTC, hash2004 commented on app/api/tests/test_tools.py
> +    print(os.environ['GOOGLE_API_KEY'])
Printing env variables is not best practice.

2024-12-18 20:40 UTC, AaronSosaRamos commented
Closed as this issue was solved in the `Develop` branch

2024-12-18 20:40 UTC, closed without merging