File Loaders
marvelai-org/marvel-ai-backend pull request #72
Opened 2024-07-10 13:10 UTC by oddblaster

Completed The following file loaders:

PPTX, HTML, PDF, IMG, PNG, Youtube, Word, etc.
Multiple functionalities can be successfully uploaded from the backend.

Issues persists with attempting to upload multiple files.

2024-07-25 20:52 UTC, mikhailocampo reviewed
See my reviews

2024-07-25 20:52 UTC, mikhailocampo commented on .vscode/launch.json
> +{
remove .vscode and related, place in .gitignore

2024-07-25 20:52 UTC, mikhailocampo commented on app/features/Kaichat/metadata.json
i think we still need this?

2024-07-25 20:52 UTC, mikhailocampo commented on app/features/quizzify/tools.py
> +# class YoutubeLoaders:
Should remove commented out features that are not in use

2024-07-25 20:52 UTC, mikhailocampo commented on app/features/quizzify/tools.py
> +        self.expected_file_types = ["xlsx", "pdf", "pptx", "csv", "docx","jpeg",'jpg',"png", "ppt", "html",]
use enums for accepted types

2024-08-27 18:32 UTC, hash2004 requested changes

2024-08-27 18:32 UTC, hash2004 commented on .vscode/launch.json
> +    // Use IntelliSense to learn about possible attributes.
Please remove unnecessary comments.

2024-08-27 18:32 UTC, hash2004 commented on app/features/Kaichat/metadata.json
This file should not be deleted.

2024-08-27 18:32 UTC, hash2004 commented on app/features/quizzify/tools.py
> +        prompt= PromptTemplate.from_template("I want you to check if there is any missing words in {text}. If there are any, I want to to autocomplete them with the most relevant word possible and ma
There are better prompting techniques. You can gain inspiration from:https://www.promptingguide.ai/techniques

2024-08-27 18:32 UTC, hash2004 commented on app/features/quizzify/tools.py
> +        prompt= PromptTemplate.from_template("I want you to check if there is any missing words in {text}. If there are any, I want to to autocomplete them with the most relevant word possible and ma
Also, prompts should be stored in txt files or constants.py file.

2024-08-27 18:32 UTC, hash2004 commented on app/requirements.txt
Add fastapi[standard]

2024-08-27 18:32 UTC, hash2004 commented on app/utils/auth.py
> +    print(api_key)
You should not print api keys. It is not considered best practice.

2024-12-18 20:40 UTC, AaronSosaRamos commented
Closed due inactivity

2024-12-18 20:40 UTC, closed without merging