Epic 7.2: Extended File Support for Flashcard Generator - Digital Guardians
marvelai-org/marvel-ai-backend pull request #81
Opened 2024-08-06 05:08 UTC by dinglunz

**Standardized Document Loading:**

- Custom loaders now yield Langchain Document objects as a list, ensuring compatibility with the load_and_summarize chain.

- Various sub-loaders are implemented for handling different document types such as PDFs, PowerPoint presentations, text files, JSON files, Markdown files, DOCX files, Azure documents, CSV files, HTML files, Google Sheets, and Google Slides.

**Text Splitting for Effective Summarization:**

- Text from documents is appropriately segmented using the RecursiveCharacterTextSplitter.

- The chunk size parameters are optimized for each type of document to ensure effective summarization.

**Integration with Map-Reduce Algorithm:**

- The load_summarize_chain from Langchain is utilized with the Map Reduce algorithm to handle the summarization of multiple documents.

- The chain processes both YouTube transcripts and documents from custom loaders, ensuring comprehensive summarization.

**Enhanced Summarization Process:**

- The summarization chain is enhanced to handle large document sets by selecting the K-nearest neighbors based on semantic relevance.

- Document embeddings are computed using OpenAIEmbeddings, and the most relevant documents are selected for summarization.

**Evaluation of Summary Quality:**

- The summary quality is evaluated by monitoring the number of batches created and the length of the summary.

- Edge cases, such as handling a large number of documents, are addressed by selecting the most relevant documents for summarization, preventing the Map Reduce algorithm from breaking.

2024-08-07 20:47 UTC, mikhailocampo reviewed
See changes requested

2024-08-07 20:47 UTC, mikhailocampo commented on app/features/dynamo/tools.py
> +            logger.error(f"Failed to load Markdown file from {self.file_type}")
Ensure the behavior of the try-except blocks are the same. In this case, it is returning an empty list while other classes' load method is raising a ValueError

2024-08-26 18:20 UTC, hash2004 requested changes
Please review the changes requested by Mikhael.

2024-12-18 20:43 UTC, AaronSosaRamos commented
Closed due inactivity

2024-12-18 20:43 UTC, closed without merging