Epic 7.7.1: Syllabus Generator - Machine Masters
marvelai-org/marvel-ai-backend pull request #82
Opened 2024-08-06 19:08 UTC by TahaKoleilat

# Syllabus Generator

This feature provides a tool to generate course syllabi based on input data provided in JSON format. The system allows users to specify various course-related details and outputs a structured syllabus.

## Features

- **Input JSON**: Define course details including subject, grade level, course description, objectives, materials, grading policy, and more.
- **Automated Syllabus Generation**: Creates a detailed syllabus based on the provided data.

## Usage

To generate a syllabus, provide an input JSON file with the necessary course information. The expected JSON structure is as follows:

```json
{
    "user": {
        "id": "string",
        "fullName": "string",
        "email": "string"
    },
    "type": "tool",
    "tool_data": {
        "tool_id": 2,
        "inputs": [
            {
                "name": "subject_topic",
                "value": "Introduction to Algebra"
            },
            {
                "name": "grade_level",
                "value": "High School"
            },
            {
                "name": "subject",
                "value": "Mathematics"
            },
            {
                "name": "course_description",
                "value": "An introductory course on algebra and geometry."
            },
            {
                "name": "course_objectives",
                "value": "To teach students the fundamentals of algebra."
            },
            {
                "name": "required_materials",
                "value": "Textbook, calculator, notebook"
            },
            {
                "name": "grading_policy",
                "value": "50% Exams, 30% Homework, 20% Participation"
            },
            {
                "name": "course_outline",
                "value": "Week 1-2: Algebra basics, Week 3-4: Geometry"
            },
            {
                "name": "class_policies",
                "value": "No late submissions, attendance required"
            },
            {
                "name": "instructor_name",
                "value": "Dr. John Doe"
            },
            {
                "name": "instructor_title",
                "value": "Professor"
            },
            {
                "name": "important_dates",
                "value": "2024-08-01 to 2024-12-15"
            },
            {
                "name": "learning_outcomes",
                "value": "Students will understand basic algebraic principles."
            },
            {
                "name": "class_schedule",
                "value": "Monday and Wednesday, 10:00 AM - 11:30 AM"
            },
            {
                "name": "instructor_contact",
                "value": "johndoe@example.com"
            },
            {
                "name": "additional_customizations",
                "value": "Include extra instructor_contact johndo@example.com in the syllabus."
            }
        ]
    }
}
```
## Sample Output
```
{
  "data": {
    "course_name": "Introduction to Algebra",
    "grade_level": "High School",
    "subject": "Mathematics",
    "course_description": "An introductory course on algebra and geometry.",
    "course_objectives": [
      "To teach students the fundamentals of algebra."
    ],
    "required_materials": [
      "Textbook",
      "Calculator",
      "Notebook"
    ],
    "grading_policy": {
      "Exams": 0.5,
      "Homework": 0.3,
      "Participation": 0.2
    },
    "course_outline": [
      {
        "week": "1-2",
        "topics": "Algebra basics"
      },
      {
        "week": "3-4",
        "topics": "Geometry"
      }
    ],
    "class_policies": [
      "No late submissions",
      "Attendance required"
    ],
    "instructor": {
      "name": "Dr. John Doe",
      "title": "Professor",
      "contact": "johndoe@example.com",
      "instructor_contact": "johndo@example.com"
    }
  }
}
```
## File Structure

- **core.py**: Contains the core logic for processing the input and generating the syllabus.
- **tools.py**: Contains helper functions and utilities for the project as well as the default input prompt to the LLM which the user can change.
- **metadata.json**: Defines the input structure and metadata for the syllabus generation tool.

## Input Data Description

The JSON input data should contain the following fields:
- `Grade Level`: The educational level for which the syllabus is intended (e.g., "High School").
- `Important Dates`: Start and end dates of the course.
- `Subject`: The subject of the course (e.g., "Mathematics").
- `Course Description`: A brief overview of the course content.
- `Learning Outcomes`: The expected outcomes for students.
- `Course Objectives`: The goals of the course.
- `Class Schedule`: Days and times the class will meet.
- `Required Materials`: Materials needed for the course.
- `Grading Policy`: Breakdown of grading criteria.
- `Course Outline`: A weekly outline of topics to be covered.
- `Class Policies`: Rules and expectations for the class.
- `Instructor Name`: The name of the course instructor.
- `Instructor Title`: The title of the course instructor.
- `Instructor Contact`: Contact information for the instructor.
- `Additional Customizations`: Any additional customization requests for the syllabus.

2024-08-07 20:54 UTC, mikhailocampo requested changes
Good work, see minor changes requested, and remove the `venv` files

2024-08-07 20:54 UTC, mikhailocampo commented on README.md
> +
PR Template looks fine, include testing methodology and results. Then, include a request schema where you define the types for each input field

2024-08-07 20:54 UTC, mikhailocampo commented on app/api/router.py
> +from services.schemas import ToolRequest, ChatRequest, Message, ChatResponse, ToolResponse
I believe we keep the prefix `app.` for importing the modules

2024-08-07 20:54 UTC, mikhailocampo commented on app/features/syllabus_generator/README.md
> +
See my notes left on README.md

2024-08-07 20:54 UTC, mikhailocampo commented on app/features/syllabus_generator/tools.py
> +    def to_dict(self) -> dict:
Use the built-in Pydantic method, `model_dump` to return the model fields as a dict rather than a new `to_dict` method

2024-08-07 20:54 UTC, mikhailocampo commented on vvvenv/Include/site/python3.12/greenlet/greenlet.h
This is a `venv` file, can remove

2024-11-16 00:20 UTC, AaronSosaRamos requested changes
Please, solve the given comments

2024-11-16 00:20 UTC, AaronSosaRamos commented on .gitignore
> +.vvvenv
Why are these environments required? Because only 1 environment is needed for now.

2024-11-16 00:20 UTC, AaronSosaRamos commented on .gitignore
> +vvvenv.bak/
Why is necessary to ignore these files?

2024-11-16 00:20 UTC, AaronSosaRamos commented on app/api/tool_utilities.py
> +from services.logger import setup_logger
You must not need to remove the app folder because it allows to avoid dependency issues.

2024-11-16 00:20 UTC, AaronSosaRamos commented on app/api/tool_utilities.py
> +    module_dir_path = os.path.join(base_dir, '..', *tool_config['path'].split('.')[:-1])
Why is this required?

2024-11-16 00:20 UTC, AaronSosaRamos commented on app/api/tool_utilities.py
> +        return execute_function(syllabus_args)
Don't harcode the `finalize_inputs` function only with the `syllabus_args`

2024-11-16 00:20 UTC, AaronSosaRamos commented on app/api/tools_config.json
> +    "2": {
Refactor the `tool_number` please

2024-11-16 00:20 UTC, AaronSosaRamos commented on app/features/quizzify/core.py
> -from app.services.tool_registry import ToolFile
You must not need to remove the app folder because it allows to avoid dependency issues.

2024-11-16 00:20 UTC, AaronSosaRamos commented on app/features/quizzify/tools.py
> -from app.services.logger import setup_logger
You must not need to remove the app folder because it allows to avoid dependency issues.

2024-11-16 00:20 UTC, AaronSosaRamos commented on app/features/syllabus_generator/core.py
> +def executor(syllabus_args: SyllabusGeneratorArgsModel, verbose: bool = True):
Good use of the Pydantic Schema for decoupling args.

2024-11-16 00:20 UTC, AaronSosaRamos commented on app/features/syllabus_generator/tools.py
> +            "prompt": (
This prompt can be in an external .txt file

2024-11-16 00:20 UTC, AaronSosaRamos commented on app/features/syllabus_generator/tools.py
> +    def __init__(self, prompt=None, customization_prompt=None, parser=None, model=None, verbose=False):
You can use a Pydantic schema for decoupling the args.

2024-11-16 00:20 UTC, AaronSosaRamos commented on app/main.py
> -from app.api.router import router
You must not need to remove the app folder because it allows to avoid dependency issues.

2024-12-18 20:43 UTC, AaronSosaRamos commented
Closed due inactivity

2024-12-18 20:43 UTC, closed without merging