Epic 7.3.1 : Worksheet Generator - Squad Robo Rebels
marvelai-org/marvel-ai-backend pull request #88
Opened 2024-08-15 18:37 UTC by ApoorvThite

### Epic 7.3.1 Worksheet Generator

Squad – Robo Rebels

Project Manager : Shrishti Singh
Team Members : Asmi Panigrahi, Shanika Perera, Apoorv Thite, Shrihari Prasad
Gopalakrishnan, Zheng Wu, Bhanu Prakash, Rohith Jatla

**Description and Formatting :**

- We created worksheet generator located features/worksheet
- We used tool ID "2". from api/tools_config.json:

![image](https://github.com/user-attachments/assets/b1407485-6614-4018-8f3b-cce0c84030a9)

Here is the configuration of our input in the features/worksheet/metadata.json:

![Screenshot 2024-08-16 at 12 05 36 AM](https://github.com/user-attachments/assets/0ddc3aad-5b2c-43aa-a824-5f752887740d)

So our request body looks like:

![image](https://github.com/user-attachments/assets/e0d739f2-9c47-458a-9ea3-43d048688785)

User Information:

- "id": "string": Placeholder for the user's unique identifier.
- "fullName": "string": Placeholder for the user's full name.
- "email": "string": Placeholder for the user's email address.

Request Type:

- "type": "tool": Indicates the type of request, which is a tool-related request.

Tool Data:

- "tool_id": 2: Identifier for the specific tool being requested.
- "inputs": An array of input parameters for the tool, including:
- "name": "grade_level", "value": 12: Specifies the grade level as 12.
- "name": "topic", "value": "Physics": Specifies the topic as Physics.
- "name": "difficulty_level", "value": "high": Specifies the difficulty level as high.
- "name": "question_type", "value": Can specify the question type (from fill-in-the-blank, multiple-choice, open-ended) upto maximum 10 questions.
- "name": "language", "value": "EN": Specifies the language of the questions as English.

<img width="677" alt="Screenshot 2024-08-13 at 2 54 37 PM" src="https://github.com/user-attachments/assets/86df77b2-1b98-4018-810b-08a9f7529626">

**Key Features :**

Worksheet Generation:

- WorksheetGenerator Class: Manages the creation of a worksheet by generating questions based on specified parameters (grade level, topic, difficulty level, question types, language).
- Question Types: Supports multiple-choice, fill-in-the-blank, and open-ended questions.
- Verbose Mode: Logs detailed information during the question generation process if enabled.

2. Question Building:

- Abstract Base Class (QuestionBuilder): Provides a blueprint for generating questions, including abstract methods for validating responses, transforming JSON data, and creating questions.

Specific Question Builders:

- MultiChoiceQuestionBuilder: Generates and validates multiple-choice questions.
- FillInBlankQuestionBuilder: Generates and validates fill-in-the-blank questions.
- OpenEndedQuestionBuilder: Generates and validates open-ended questions.
- Prompt and Model Configuration: Each question builder uses a specific prompt and Google Gemini model for generating questions.

3. Custom JSON Parsing and Validation:

- Custom Parsers: Uses Pydantic models (MultiChoiceQuestion, FillInBlankQuestion, OpenEndedQuestion) to parse and validate the structure of generated questions.
- JSON Schema Examples: Each Pydentic model includes JSON schema examples for the expected format of the questions.

4. Logging:

- Setup Logger: A logger is configured to log messages at various points in the code, especially for tracking question generation attempts and validation results.

5. Error Handling:

- Validation Checks: The code includes error handling for invalid inputs, such as missing parameters or improperly formatted responses.
- Retry Mechanism: If a question fails to generate or validate correctly, the system attempts to generate a new question, with a limit on the number of retries.

6. File Handling:

- Read Text Files: A helper function (read_text_file) is used to read prompt templates from text files based on a relative path.

7. Extensibility:

- Flexible Design: The system is designed to allow the addition of new question types by extending the QuestionBuilder abstract class and registering the new builder in the question_builder_classes mapping.

**Code Structure:**

- Logger Setup: We've initialized a logger using setup_logger() to handle logging throughout the function.
- Function Definition: We've defined a function named executor, which accepts parameters such as grade_level, topic, difficulty_level, question_types, lang, and an optional verbose flag.
- Debug Logging (Conditional): We've included a conditional debug log that activates if the verbose flag is set to True, logging the provided parameters (grade_level, topic, difficulty_level, question_types, lang).
- Parameter Setup: We've created a dictionary named params that contains the values for grade_level, topic, difficulty_level, question_types, lang, and verbose.
- Worksheet Generation: We've instantiated a WorksheetGenerator object using the params dictionary and called its create_worksheet method to generate and return the questions for the worksheet.
- Output Assignment: The generated worksheet questions are stored in the output variable.

For Testing purposes, we limited the num_questions to 10. We might increase the allowed limit of questions to make the system more optimised to handle larger number of questions as per requirement.

For generating questions, in our tools.py file, we created the following classes 

The MultiChoiceQuestion class validates and structures multiple-choice question data, ensuring it includes the question text, a list of choices, and the correct answer key. It also provides an example schema for clarity and consistency in data formatting.

![image](https://github.com/user-attachments/assets/633aa8db-c492-4df3-83ad-5f6d64f0f2c4)

The FillInBlankQuestion class ensures that fill-in-the-blank question data includes both the question text with a blank and the correct answer. It also includes an example schema within json_schema_extra to demonstrate the expected data format for clarity and validation purposes.

![image](https://github.com/user-attachments/assets/f3165d8b-1678-4cc5-a5c4-481d11ca7b3c)

The OpenEndedQuestion class ensures that open-ended question data includes both the question text and the correct answer. It also provides an example schema within json_schema_extra to demonstrate the expected data format for validation and consistency.

![image](https://github.com/user-attachments/assets/0678d0ba-f66d-4e3d-91d4-7370358446cb)

**Testing:**

Testing our code involved ensuring that each component functioned correctly and integrated seamlessly with the others. 

- Given the various classes and methods involved, we first performed unit tests to validate the functionality of individual classes like WorksheetGenerator, MultiChoiceQuestionBuilder, FillInBlankQuestionBuilder, and OpenEndedQuestionBuilder. 
- For each of these classes, we created test cases that simulated different input scenarios, such as varying grade levels, topics, difficulty levels, and question types. 
- For instance, when testing the MultiChoiceQuestionBuilder, we checked whether it generated questions with the correct structure, validated the generated responses, and ensured the format of choices was accurate. Similarly, we tested the FillInBlankQuestionBuilder and OpenEndedQuestionBuilder to confirm they correctly generated and validated their respective question types.

Different use cases for testing included varying combinations of input parameters to ensure robustness. 
- For example, we tested the system with edge cases like the maximum number of questions (e.g., 10), as well as invalid inputs, such as an unsupported question type or missing required parameters like grade_level or topic, in addition to the general responses of different topic, grade level, diffculty level, type of questions and language.
- Another use case involved testing the verbose mode to confirm that detailed logs were produced during question generation, helping us trace any issues that arose. Additionally, we simulated scenarios where the model might generate respons [...]

2024-08-21 21:13 UTC, hash2004 commented on app/services/tool_registry.py
No need to include this, core.py should use tool file

2024-08-21 21:14 UTC, hash2004 requested changes
Great job! Please review the changes requested

2024-11-15 21:52 UTC, AaronSosaRamos requested changes
Please, solve the given comments.

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/core.py
> +def executor(grade_level : int, topic: str, difficulty_level: str, question_types: list[WorkSheetQuestionType], lang: str, verbose=False):
You can use a Pydantic Schema for decoupling these args.

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/core.py
> +        params = {"grade_level": grade_level, "topic": topic, "difficulty_level": difficulty_level, "question_types": question_types, "lang": lang, "verbose": verbose}
This can be solved using a Pydantic schema

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/metadata.json
> +            "label": "ISO 639-1 Language Code",
Good use of standards

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +from langchain_core.pydantic_v1 import BaseModel, Field
Refactor this to `from pydantic` as it is not compatible anymore with LangChain v. 0.3

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +    def __init__(self, grade_level, topic, difficulty_level, question_types, lang, verbose=False):
You can use a Pydantic Schema for decoupling args.

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +        params = {"grade_level": self.grade_level, "topic": self.topic, "difficulty_level": self.difficulty_level, "lang": self.lang, "verbose": self.verbose}
Use a Pydantic Schema for this.

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +        parsed_output = self.parser.parse(output)
Please, use LCEL as: `prompt | llm | parser` for best practices about enhancing AI pipelines effectively

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +class MultiChoiceQuestionBuilder(QuestionBuilder):
Good use of OOP for better reusability.

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +    def __init__(self, grade_level, topic, difficulty_level, lang, prompt=None, model=None, parser=None, verbose=False):
Use a Pydantic schema for decoupling these args.

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +            "model": GoogleGenerativeAI(model="gemini-1.0-pro"),
Refactor this model to `gemini-1.5-flash` or `gemini-1.5-pro` as v. 1.0 is not working anymore.

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +    def validate_response(self, response: Dict) -> bool:
This validation is not required if the use of the JSONOutputParser is effectively done with the given prompt.

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +    def format_choices(self, choices: Dict[str, str]) -> List[Dict[str, str]]:
This formatting is done by the Parser

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +        while len(generated_questions) < num_questions and attempts < max_attempts:
Check if the use of a `while` loop is not costful for the LLM

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +            if self.validate_response(response):
This validation is actually done by the parser.

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +    def validate_response(self, response: Dict) -> bool:
This validation is not required if the use of the JSONOutputParser is effectively done with the given prompt.

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +        while len(generated_questions) < num_questions and attempts < max_attempts:
Check if the use of a while loop is not costful for the LLM

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +            if (not 'properties' in response):
This validation is actually done by the parser.

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +    def transform_json_dict(self, input_data: Dict) -> Dict:
This validation can be done with the JSONOutputParser.

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +    def validate_response(self, response: Dict) -> bool:
This validation is not required if the use of the JSONOutputParser is effectively done with the given prompt.

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +        while len(generated_questions) < num_questions and attempts < max_attempts:
Check if the use of a while loop is not costful for the LLM

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +            if 'properties' in response:
This validation is actually done by the parser.

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +question_builder_classes = {
Use enums for this.

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +    model_config = {
Good use of `model_config` for a deterministic output

2024-11-15 21:52 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +    "multiple-choice": MultiChoiceQuestionBuilder,
Check if you can divide your code in order to ensure a better readability and the Single Responsability principle

2024-12-18 20:46 UTC, AaronSosaRamos commented
Closed due inactivity

2024-12-18 20:46 UTC, closed without merging