Initial commit: Complete application setup with code, tests, and Dock…
marvelai-org/marvel-ai-backend pull request #90
Opened 2024-08-16 06:45 UTC by sanjana3014

# Pull Request - Support for Multiple File Types in Worksheet Generator

## Summary
This pull request introduces support for multiple file types in the Worksheet Generator, enhancing the tool's flexibility and usability. The feature allows users to upload and process a variety of file formats, including PDF, DOCX, PPTX, HTML, images (PNG, JPG, JPEG), audio (WAV, MP3), and video (MP4). This enhancement solves the problem of limited input file formats and enables broader applicability of the tool in different scenarios.

## Changes
- **DocumentProcessor Class**: 
  - Added methods to process new file types including images, audio, and video.
  - Refactored `ingest_documents` method to handle various file formats.
- **EmbeddingClient Class**:
  - Integrated with VertexAIEmbeddings to support the new input formats.
- **ChromaCollectionCreator Class**:
  - Adjusted to handle the chunking and embedding of content from the new file types.
- **QuizGenerator Class**:
  - Modified to generate quizzes from the expanded list of file types.
- **Testing**:
  - Added new unit tests in `test_tools.py` to cover the new file types.
  - Created integration tests to validate the end-to-end workflow with the new formats.
- **Dockerfile**:
  - Updated to include necessary libraries for processing the additional file types.
- **Metadata.json**:
  - Adjusted to reflect the new input parameters and file types.

## Testing
- **Unit Tests**:
  - Developed unit tests for each method in the `DocumentProcessor` to ensure correct processing of all supported file types.
  - Added tests for `EmbeddingClient` and `QuizGenerator` to verify the correct functioning with new file types.
- **Integration Tests**:
  - Performed end-to-end testing using FastAPI's /docs page.
  - Verified the correct ingestion, processing, and quiz generation using sample files in each supported format.
- **Additional Testing**:
  - Conducted local testing using Docker to ensure the entire setup works in a fresh environment.
  - Tested the application using a local server to verify that the tool works as expected with the new input types.

## Results
The new feature has been thoroughly tested and is functioning as intended. All unit tests passed successfully, demonstrating good coverage of the new functionalities. Integration tests confirmed that the entire workflow—file ingestion, processing, and quiz generation—works smoothly across all supported file types.

## Notes
- This feature allows the Worksheet Generator to support a broad range of file formats, making it more versatile and useful in various contexts.
- Future improvements could include optimizing the processing time for large files and adding support for additional file formats like XML and JSON.

## Screenshots
![ss1](https://github.com/user-attachments/assets/52e1e55a-9ee5-46f1-b59c-e72bcc260bb0)
![ss2](https://github.com/user-attachments/assets/0f2e0e7d-0fe5-442f-a397-ac2767da7c26)
![ss3](https://github.com/user-attachments/assets/a83c6ada-57d6-4a29-9f77-96467e554cd4)
![ss4](https://github.com/user-attachments/assets/446b3ae3-7b6d-4cd8-83f1-3522d4424570)
![DocumentProcessor](https://github.com/user-attachments/assets/03eef995-e876-4a1e-8574-8a55f9a022f6)
![Document_Processor](https://github.com/user-attachments/assets/517ccaf6-46f0-44a1-91ae-e58e1837b135)

## How to Test
1. Clone the repository and check out the `multiple-file-types` branch.
2. Set up the environment by following the instructions in the `README.md`.
3. Run the application locally using Docker or by setting the necessary environment variables and running `uvicorn`.
4. Use the FastAPI `/docs` page to test the new file types by uploading sample files and verifying the correct processing and quiz generation.

2024-08-21 20:27 UTC, mikhailocampo requested changes
See changes, should not be using streamlit for the API on expeditions

2024-08-21 20:27 UTC, mikhailocampo commented on app/features/tests/test_tools.py
Document tests such as assertions made and what are the results of the tests

2024-08-21 20:27 UTC, mikhailocampo commented on app/features/worksheet_generator/core.py
We cannot use Streamlit for this expedition

2024-08-21 20:27 UTC, mikhailocampo commented on app/features/worksheet_generator/tools.py
> +class DocumentProcessor:
Better to split into subclasses for separation of concerns in SOLID principle

2024-08-21 20:27 UTC, mikhailocampo commented on app/features/worksheet_generator/tools.py
> +                if file_extension == ".pdf":
Define these as enums and handle them within their respective subclasses for better readability

2024-11-17 15:05 UTC, AaronSosaRamos requested changes
Please, solve the given comments.

2024-11-17 15:05 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/home/sanjana3014/kai-ai-backend_/local-auth.json"  # Ensure this is the correct path
This is hardcoded. Please, use dotenv with the .env file for best practices.

2024-11-17 15:05 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +        uploaded_files = st.file_uploader("Upload files", type=['pdf', 'png', 'mp4', 'docx', 'xlsx', 'csv', 'pptx', 'html', 'jpg', 'jpeg', 'wav', 'mp3'], accept_multiple_files=True)
Please, use enums for decoupling the available file types.

2024-11-17 15:05 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +                    loader = PyPDFLoader(temp_file_path)
As @mikhailocampo mentioned, you can use enums for better scalability and reuse these components. You can try creating a reusable function for this.

2024-11-17 15:05 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +            self.client = VertexAIEmbeddings(
VertexAI is not used anymore in the main project.

2024-11-17 15:05 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +        self.system_template = """
You can try using a prompt in a separated file for better maintainability and keeping DRY.

2024-11-17 15:05 UTC, AaronSosaRamos commented on app/features/worksheet_generator/tools.py
> +        self.llm = VertexAI(
VertexAI is not used anymore in the main project.

2024-12-18 20:47 UTC, AaronSosaRamos commented
Closed due inactivity

2024-12-18 20:47 UTC, closed without merging