Squad Cognitive Crew Kai 7.2 Project Pull Request
marvelai-org/marvel-ai-backend pull request #97
Opened 2024-08-26 17:15 UTC by PuneetPowar5

Squad Cognitive Crew has finally completed their version of KAI 7.2 and it is ready to be checked before merging into the main branch. The PR request template has been attached to this request as well.
[PR request template.pdf](https://github.com/user-attachments/files/16751652/PR.request.template.pdf)

2024-08-26 18:04 UTC, hash2004 requested changes
Please explain the changes you make by following the PR template. Thank you!

2024-08-26 18:04 UTC, hash2004 commented on app/features/dynamo/doc_type_processors/ppt_processor.py
> +            "You are a flashcard generation assistant designed to help students analyze a document and return a list of flashcards. "
You can use .txt file to store prompts and import it from there.

2024-08-26 18:04 UTC, hash2004 commented on app/features/dynamo/doc_type_processors/test_ppt_processor.py
> +class MockVertexAI:
Why are we mocking the VertexAI API if its not available with an empty class? Instead do robust error handling and edge case handling.

2024-08-26 18:04 UTC, hash2004 commented on app/features/dynamo/tools.py
> -def summarize_transcript(youtube_url: str, max_video_length=600, verbose=False) -> str:
max_video_length is a necessary part of the application. Please include it in the parameters as before.

2024-08-26 18:04 UTC, hash2004 commented on app/features/dynamo/tools.py
> +        chain_type='stuff'
Haha, this is not the correct way to handle edge cases. Please revise the code.

2024-12-18 20:47 UTC, AaronSosaRamos commented
Closed due inactivity

2024-12-18 20:47 UTC, closed without merging