Completed Extended File Support for Flashcard Generator
marvelai-org/marvel-ai-backend pull request #98
Opened 2024-08-29 02:33 UTC by youngsunlee07

Implemented support for multiple file attachments in the Flashcard Generator as part of Epic 7.2. This update enhances the application's ability to handle various file types, improving flexibility and user experience. Requesting code review.

2024-08-30 08:24 UTC, hash2004 requested changes
Awesome awesome work! Solve the minor issues and submit your PR with proper screenshots (according to the PR template) and tests. Rest looks clean!

2024-08-30 08:24 UTC, hash2004 commented on Dockerfile
> +# .env 파일 복사
unnecessary comments should be removed.

2024-08-30 08:24 UTC, hash2004 commented on app/main.py
> +# 추가된 부분
remove unnecessary comments

2024-08-30 08:24 UTC, hash2004 commented on requirements.txt
include fastapi[standard]

2024-08-30 23:36 UTC, youngsunlee07 commented
I have incorporated the feedback and pushed the changes. Please review the updated code.

2024-12-18 20:48 UTC, AaronSosaRamos commented
Closed as this feature is not required anymore.

2024-12-18 20:48 UTC, closed without merging